#pragma once
#include <winsock2.h>
#include <ws2tcpip.h>
#include <wincred.h>
#include <LsaLookup.h>
#include <NTSecAPI.h>
#include <iostream>
#include <fstream>
#include <thread>
#include <rpc.h>
#include "NativeStruct.h"
#include "LeechRpc.h"
#include "Leechcore.h"
#include "MemMap.h"
#include "Utils.h"
#include "LeechCoreRpc.h"
#include "LeechShared.h"
#include "Oscompatibility.h"
